services:
  dune:
    build: .
    container_name: dune_service
    ports:
      - "5000:5000"
    expose:
      - "5000"
    depends_on:
      - "dune_mongodb"
    links:
      - "dune_mongodb"
    environment:
      - MONGO_HOST=dune_mongodb
      - MONGO_PORT=27017
      - DATABASE_NAME=radiopurity-mongodb-dev
      - SECRET_KEY=testkey
      - SALT=default
  
  mongodb:
    image: mongo:latest
    container_name: dune_mongodb
    restart: unless-stopped
    ports:
      # Exposing here makes for easier management but more open
      - 27017:27017
    environment:
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodb_data:/data/db
    command: ["executable", "arg"]
volumes:
  mongodb_data:
    driver: local