version: "2"
services:
  flask:
    build: .
    expose:
      - "5000"
    depends_on:
      - "mongoservice"
    links:
      - "mongoservice"
  mongoservice:
    image: mongo:latest
    container_name: duneui_mongodb
    restart: unless-stopped
    ports:
      # Exposing here makes for easier management but more open
      - 27017:27017
    environment:
      MONGODB_DATA_DIR: /data/db
    volumes:
      - mongodb_data:/data/db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - "flask"
volumes:
  mongodb_data:
    driver: local
