FROM ubuntu:16.04

# install python3.8
RUN apt-get update && apt-get install -y \
  software-properties-common build-essential git curl vim zip wget

RUN add-apt-repository ppa:deadsnakes/ppa 
RUN apt-get update && apt-get install -y \
  python3.8 python3.8-dev python3.8-venv && \
  apt-get update && \
  apt-get clean && \
  apt-get autoremove

# install pip
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && python3.8 get-pip.py

# make python3.8 the default version for the python3 command
RUN rm -f /usr/bin/python3 && ln -s /usr/bin/python3.8 /usr/bin/python3

# clone git repo
WORKDIR /home/
RUN git clone https://github.com/pnnl/Radiopurity-database-assistant.git && cd /home/Radiopurity-database-assistant && git checkout snolab-version

# install python packages and dunetoolkit
RUN cd /home/Radiopurity-database-assistant && python3 setup.py install
RUN cd /home/Radiopurity-database-assistant && pip install -r user_interface/requirements.txt
RUN pip install selenium beautifulsoup4 webdriver-manager

WORKDIR /home/Radiopurity-database-assistant/user_interface

# install google chrome binary, chromedriver (version 91)
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y -f ./google-chrome-stable_current_amd64.deb
RUN wget https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip && unzip chromedriver_linux64.zip

# for testing the flask app
COPY ./user_interface/app_config_docker_test.json /home/Radiopurity-database-assistant/user_interface/app_config_test.json
COPY ./dunetoolkit/toolkit_config_docker_test.json /home/Radiopurity-database-assistant/dunetoolkit/toolkit_config_test.json
COPY ./user_interface/DUNEreader_creds.txt /home/Radiopurity-database-assistant/dunetoolkit/DUNEreader_creds.txt
COPY ./user_interface/DUNEwriter_creds.txt /home/Radiopurity-database-assistant/dunetoolkit/DUNEwriter_creds.txt

# set test config environment variable names
ENV DUNE_API_CONFIG_NAME=/home/Radiopurity-database-assistant/user_interface/app_config_test.json
ENV TOOLKIT_CONFIG_NAME=/home/Radiopurity-database-assistant/dunetoolkit/toolkit_config_test.json

# default command
ENTRYPOINT ./run_test.sh

